name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ 1. Obtiene el código del repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # ✅ 2. Configura Buildx para multi-arquitectura
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # ✅ 3. Inicia sesión en Docker Hub con secretos
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # ✅ 4. Construye y sube la imagen
        with:
          context: .  # Usa el directorio actual
          push: true  # Lo sube al registro
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
